### ISSUE TITLE
Jumbotron issue

### ISSUE THREAD

**Issue by cameronoelsen** [cameronoelsen/jupytersite#4]
Hey @Carreau!

I am having a problem with the jumbotron at the top of the landing page. We are putting multiple svgs on top of each other to use css animations to have the rings fade in. When we do this, it causes a white gap to appear on the right side of the page. You can see it most prominently at the bottom near the footer if you scroll right. I think this is causing the problem but I am not sure how to fix it. Auberon and I have been trying to figure it out for the last hour or so. Thanks so much again!

**Comment by cameronoelsen** [comment]
Nevermind, Jon Frederic fixed it with a quick overflow: hidden tag!

**Comment by Carreau** [comment]
Sorry was travelling.
